# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Cuidador',
                'verbose_name_plural': 'Cuidadores',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.SmallIntegerField(verbose_name='Idade')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
