# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_cuidador_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='idade',
        ),
        migrations.AddField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.DateField(default=datetime.datetime(2019, 4, 3, 3, 3, 18, 846418, tzinfo=utc), verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
