# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-11 02:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afericao',
            name='dt_criacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 2, 54, 32, 205942, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
