# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-11 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0002_auto_20190410_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afericao',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
    ]
