# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-11 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0003_auto_20190410_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afericao',
            name='dt_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
