# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssvv', '0002_remove_sinal_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sinal',
            options={'ordering': ['nome'], 'verbose_name': 'Sinal', 'verbose_name_plural': 'Sinais'},
        ),
    ]
